
wallpaper {
    monitor = 
    path = /home/shaurm1sa/.config/hypr/wallpapers/reze.png
    fit_mode = cover
    timeout = 3600
}

wallpaper {
    monitor = 
    path = /home/shaurm1sa/.config/hypr/wallpapers/gojo1.jpeg
    fit_mode = cover
    timeout = 3600
}

wallpaper {
    monitor = 
    path = /home/shaurm1sa/.config/hypr/wallpapers/jujutsu.jpeg
    fit_mode = cover
    timeout = 3600
}

wallpaper {
    monitor = 
    path = /home/shaurm1sa/.config/hypr/wallpapers/gojo2.jpeg
    fit_mode = cover
    timeout = 3600
}

wallpaper {
    monitor = 
    path = /home/shaurm1sa/.config/hypr/wallpapers/sukuna.png
    fit_mode = cover
    timeout = 3600
}
