hl.on("hyprland.start", function ()
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("waybar")
  hl.exec_cmd("kanshi")
  hl.exec_cmd("dunst")
  hl.exec_cmd("udiskie -t")
end)
